//const baseUri='http://192.168.0.107/DBThings';
const baseUrl='http://localhost:8888'
const apiUrl={
    //登录
    login:baseUrl+'/login',
    //分页条件获取所有学生信息
    selectStudentByConditionAndPage:baseUrl+'/selectStudentByConditionAndPage',
    //根据学号删除学生信息
    deleteStudentByNo:baseUrl+'/deleteStudentByNo',
    //批量删除学生
    deleteMultipleStudent:baseUrl+'/deleteMultipleStudent',
    //手动添加学生
    addStudent:baseUrl+'/addStudent',
    //获取所有学院信息
    selectAllDepartment:baseUrl+'/selectAllDepartment',
    //批量添加学生
    addMultipleStudent:baseUrl+'/addMultipleStudent',
    //获取所有学生信息
    selectAllStudents:baseUrl+'/selectAllStudents',
    //根据学号获取学生信息
    selectStudentByNo:baseUrl+'/selectStudentByNo',
    //修改学生信息
    updateInfo:baseUrl+'/updateInfo',
    //条件分页获取所有教师信息
    selectTeacherByPageAndCondition:baseUrl+'/selectTeacherByPageAndCondition',
    //获取所有课程信息
    selectAllCourse:baseUrl+'/selectAllCourse',
    //添加单个老师
    addTeacher:baseUrl+'/addTeacher',
    //删除单个教师
    deleteTeacherByNo:baseUrl+'/deleteTeacherByNo',
    //删除多个教师
    deleteMultipleTeacher:baseUrl+'/deleteMultipleTeacher',
    //获取所有老师信息
    selectAllTeacher:baseUrl+'/selectAllTeacher',
    //根据tno查询教师信息
    selectTeacherBytno:baseUrl+'/selectTeacherBytno',
    //修改教师信息
    updateTeacherInfo:baseUrl+'/updateTeacherInfo',
    //分页查看所有学院信息
    selectDepartmentByPageAndCondition:baseUrl+'/selectDepartmentByPageAndCondition',
    //添加学院
    addDepartment:baseUrl+'/addDepartment',
    //删除单个学院信息
    deleteDepartment:baseUrl+'/deleteDepartment',
    //删除多个学院信息
    deleteMultipleDepartment:baseUrl+'/deleteMultipleDepartment',
    //分页条件查询所有课程信息
    selectCourseByPageAndCondition:baseUrl+'/selectCourseByPageAndCondition',
    //添加课程
    addCourse:baseUrl+'/addCourse',
    //获取所有课程信息用于excel的导出
    selectAllCourses:baseUrl+'/selectAllCourses',
    //删除多个课程
    deleteMultipleCourse:baseUrl+'/deleteMultipleCourse',
    //删除单个课程
    deleteCourseByNo:baseUrl+'/deleteCourseByNo',
    //根据课程号获取详细信息
    selectCourseByCno:baseUrl+'/selectCourseByCno',
    //修改课程信息
    updateCourseInfo:baseUrl+'/updateCourseInfo',
    //分页条件查看所有选课信息
    selectSctByPageAndCondition:baseUrl+'/selectSctByPageAndCondition',
    //查看所有选课信息
    selectAllSct:baseUrl+'/selectAllSct',
    //删除一个选课信息
    deleteSctBySno:baseUrl+'/deleteSctBySno',
    //删除多个选课信息
    deleteMultipleSct:baseUrl+'/deleteMultipleSct',
    //根据学号、工号、课程号查看选课信息详情
    selectSctByNos:baseUrl+'/selectSctByNos',
    //修改选课的成绩
    changeGradeByNos:baseUrl+'/changeGradeByNos',
    //添加选课信息
    addSct:baseUrl+'/addSct',
    //获取学生报表数据
    studentStatistic:baseUrl+'/studentStatistic',
    //学院总数
    departmentCount:baseUrl+'/departmentCount',
    //查看学院总人数和男女比例
    selectDepartmentRate:baseUrl+'/selectDepartmentRate',
    //教师总数
    teacherCounts:baseUrl+'/teacherCounts',
    //教师学历男女比例
    selectTeacherOrderByTeb:baseUrl+'/selectTeacherOrderByTeb',
    //教师职称男女比例
    selectTeacherOrderByTpt:baseUrl+'/selectTeacherOrderByTpt',
    //根据学分划分课程
    selectCourseGroupByCcredit:baseUrl+'/selectCourseGroupByCcredit',
    //查看课程总量
    courseCounts:baseUrl+'/courseCounts',
    //每门课程多少学生修
    studyCourseFromStudent:baseUrl+'/studyCourseFromStudent',
    //每个学生修了多少门课
    studentStudyCourse:baseUrl+'/studentStudyCourse',
    //根据旧密码修改新密码
    updatePasswordByPreviewPassword:baseUrl+'/updatePasswordByPreviewPassword',
    //根据学号查看个人详细信息
    selectStudentInfoBySno:baseUrl+'/selectStudentInfoBySno',
    //修改密码
    findPassword:baseUrl+'/findPassword',
    //根据dno查看院系详细信息
    selectDepartmentByNo:baseUrl+'/selectDepartmentByNo',
    //修改院系信息
    updateDepartmentInfo:baseUrl+'/updateDepartmentInfo',
    //根据学号分页条件查看我的选课信息
    selectSctByPageAndConditionAndSno:baseUrl+'/selectSctByPageAndConditionAndSno',
    //根据学号分页条件查看我的选课信息,用于excel的导出
    selectAllSctByNo:baseUrl+'/selectAllSctByNo',
    //根据学号修改身份证号
    changeSidBySno:baseUrl+'/changeSidBySno',
    //每门课程多少学生修,用于导出excel
    studyCourseFromStudentToExcel:baseUrl+'/studyCourseFromStudentToExcel',
    //每个学生修了多少门课，用于导出excel的数据
    studentStudyCourseToExcel:baseUrl+'/studentStudyCourseToExcel',
}
export default  apiUrl